name: FinEdu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.1
  http: ^1.5.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.2.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.31.0 # <--- MOVIDO AQUÍ
  showcaseview: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/svg/
    - assets/img/png/
    - assets/img/icon/ # <--- Asegúrate de que esta carpeta exista

# --- ESTAS SECCIONES VAN FUERA DE "flutter:" Y SIN ESPACIOS AL INICIO ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon/logo_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/icon/logo_app.png"

flutter_native_splash:
  color: "#f8f6e9"
  image: "assets/img/icon/logo_app.png"
  
  # Quitamos gravity y los demás que dieron error
  android_12:
    image: "assets/img/icon/logo_app.png"
    color: "#f8f6e9"
  
  fullscreen: true