// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRg8PirfHQkk9e2TwqrDRaedQGz3pb24',
    appId: '1:195831746860:web:a75bd80b44f4e25f689c89',
    messagingSenderId: '195831746860',
    projectId: 'findedu-8021c',
    authDomain: 'findedu-8021c.firebaseapp.com',
    storageBucket: 'findedu-8021c.firebasestorage.app',
    measurementId: 'G-ZRNJ3ZV3VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK38dliIWxrLnOeGiZQaj8lR0_-XiX15o',
    appId: '1:195831746860:android:65f1a960e3455181689c89',
    messagingSenderId: '195831746860',
    projectId: 'findedu-8021c',
    storageBucket: 'findedu-8021c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dwT6SMsRGjDwzgdjFXxo_4E0b1VqCTM',
    appId: '1:195831746860:ios:c7090a8d84d319b2689c89',
    messagingSenderId: '195831746860',
    projectId: 'findedu-8021c',
    storageBucket: 'findedu-8021c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dwT6SMsRGjDwzgdjFXxo_4E0b1VqCTM',
    appId: '1:195831746860:ios:c7090a8d84d319b2689c89',
    messagingSenderId: '195831746860',
    projectId: 'findedu-8021c',
    storageBucket: 'findedu-8021c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRg8PirfHQkk9e2TwqrDRaedQGz3pb24',
    appId: '1:195831746860:web:191955b97965f263689c89',
    messagingSenderId: '195831746860',
    projectId: 'findedu-8021c',
    authDomain: 'findedu-8021c.firebaseapp.com',
    storageBucket: 'findedu-8021c.firebasestorage.app',
    measurementId: 'G-LQR1V3EPD6',
  );
}
